### ISSUE TITLE
it installs alright but it can't get activated

### ISSUE THREAD

**Issue by gontz** [u3dreal/molecular-plus#11]
https://i.imgur.com/q3RH0Bx.png

**Comment by u3dreal** [comment]
PLZ state OS and Blender Version 

seems like you are missing something ... oh one moment

**Comment by u3dreal** [comment]
Can you try this version

https://github.com/u3dreal/molecular-plus/actions/runs/902713950

**Comment by gontz** [comment]
same problem,
win10, blender 2.93  installing file version 1.1.5 _39
https://i.imgur.com/AZcnc5j.png

**Comment by u3dreal** [comment]
Oh something more was missing
you will have to wait till the action finishes

https://github.com/u3dreal/molecular-plus/actions/runs/902747957

**Comment by u3dreal** [comment]
Now it should work

**Comment by gontz** [comment]
yes, it works. Thank you
