### ISSUE TITLE
Cubesurfer integration?

### ISSUE THREAD

**Issue by shankarsivarajan** [u3dreal/molecular-plus#12]
Could you update cubesurfer (or recommend a similar isosurface mesher) to work with this addon? As is, it's great for sand and the like, but not very good for fluid simulations. I tried [this](https://github.com/porkminer/CubeSurfer), but it doesn't work, at least with Blender 2.93 and Windows.

**Comment by shankarsivarajan** [comment]
I have updated [CubeSurfer](https://github.com/shankarsivarajan/CubeSurfer) to work with Blender 2.93. I have only compiled the Cython for Windows though.

**Comment by u3dreal** [comment]
Nice work

**Comment by u3dreal** [comment]
I forked the repo and a macos intel version can be found here.
[https://github.com/u3dreal/CubeSurfer](url)
