### ISSUE TITLE
appears in the physics tab, but there's no entry in the particle tab, and it doesn't appear to do anything blender 3.0 alpha

### ISSUE THREAD

**Issue by 3d-illusions** [u3dreal/molecular-plus#14]
appears in the physics tab, but there's no entry in the particle tab, and it doesn't appear to do anything blender 3.0 alpha

**Comment by 3d-illusions** [comment]
appears in the physics tab, but there's no entry in the particle tab, and it doesn't appear to do anything blender 3.0 alpha and 2.93 official release.

**Comment by u3dreal** [comment]
There are no options in the particles panel any more ... look in the N Panel ( Press N in viewport )

**Comment by 3d-illusions** [comment]
ah ok, thanks.  Are there any up to date tutorials?

**Comment by u3dreal** [comment]
No ... i think there is a new one on yt ... somewhere . Join the discord i think i posted it there
