### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by Trelligan** [u3dreal/molecular-plus#16]
`Blender 3.93+ -> use Python 39 version`
   I wanted to download 1.1.7, but scrolled down as far as 1.1.5 to figure out the '37' and '39'. The line above is incorrect, I think you mean `Blender 2.93...`
   Thank you for this project, I'm here because Steven Scott recommended you.

**Comment by u3dreal** [comment]
37 and 39 is the corresponding python version used by blender.

**Comment by u3dreal** [comment]
fixed

**Comment by Trelligan** [comment]
Yes, I understand. When I read that I saw the typo: Blender 3.93.

    On Friday, December 17, 2021, 11:44:56 PM PST, u3dreal ***@***.***> wrote:  
 
 


37 and 39 is the corresponding python version used by blender.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
