### ISSUE TITLE
UV Baking

### ISSUE THREAD

**Issue by InfinityGOD** [u3dreal/molecular-plus#18]
When I tried to bake UV blender always crashes, I didn't know what could go wrong here( my desktop, the addon or blender itself). Have a pretty strong machine with 3060 32gigs and i5 10400 so I don't think that's a problem
I'll put my file below.
Thanks in advance
[Test4.zip](https://github.com/u3dreal/molecular-plus/files/8007998/Test4.zip)
e

**Comment by InfinityGOD** [comment]
Blender 3.0
Win 10 pro
Molecular version
[molecular-plus_1.1.7_39_win.zip](https://github.com/u3dreal/molecular-plus/releases/download/1.1.7/molecular-plus_1.1.7_39_win.zip)

**Comment by u3dreal** [comment]
Hm have no time now could you investigate futher ? console log ..?

**Comment by InfinityGOD** [comment]
Here's the crash log.
Also I'm not in a rush so no worries ^^
[moontetst4.crash.txt](https://github.com/u3dreal/molecular-plus/files/8008108/moontetst4.crash.txt)

**Comment by u3dreal** [comment]
Hmm no idea ...

**Comment by 3dpro45** [comment]
i have the same prob. pls help out. i cant do any molecular ragdolls.

**Comment by fernandopoulos8** [comment]
same problem, any solution??

**Comment by u3dreal** [comment]
Should be fixed here

https://github.com/u3dreal/molecular-plus/actions/runs/3351123415
