### ISSUE TITLE
Installation of the lastest add-on version failed on blender 3.1.0

### ISSUE THREAD

**Issue by gluttonium** [u3dreal/molecular-plus#21]
Installing the version "**molecular-plus_1.1.8_310_win**" for blender 3.1.0 worked fine without running into any problems.
Version "**molecular-plus_1.1.8_37_win**" also works fine but I want to use the latest version.

However the latest version "**molecular-plus_1.1.8_39_win**" can't be installed and gives me an error message:

![grafik](https://user-images.githubusercontent.com/98273272/161268153-34d6d7a9-50b1-4b4e-889e-893befaeb7db.png)

I don't know what that means, I don't code... 🤔

**Comment by u3dreal** [comment]
Blender 3.1 needs python 3.10.
