### ISSUE TITLE
Wrong MacOs Linking behaviour

### ISSUE THREAD

**Issue by Alletkla** [u3dreal/molecular-plus#22]
Hello,
I really appreciate your work. Although I'm a decent programmer I didn't have time to understand the code.

But I (potentially) found a bug in the macOS version:
Screenshot MacOs
![image](https://user-images.githubusercontent.com/65451851/180607253-ab9c2785-5ff1-4f10-8c3d-c85665bdf3f7.png)

Screenshot Windows:
![image](https://user-images.githubusercontent.com/65451851/180607269-ffac7e6a-0e83-4b06-b108-3f3e950412b3.png)

I'm on Vacation and wanted to do some work. But I noticed that on the MacOS Version there are no new links created after birth.

I'am using the same blender file, version and same Python version on both machines.

Blender Version: 3.2.1
python: 3.10.2

Thanks for your help.

If you have tip, where I can start diving into the code, maybe I can help (in upcoming issues)

**Comment by u3dreal** [comment]
Can not confirm all works well here ... 3.2.2 and lastes molecular+
