### ISSUE TITLE
Baking stutters and repeats playback.

### ISSUE THREAD

**Issue by TestPilot02** [u3dreal/molecular-plus#23]
Hi, I've installed 1.19 310 Win on Windows 11 Blender 3.3.

When I click bake it begins, but the animation often jumps back to the start position and repeatedly plays out the simulation from the beginning. This stuttering and repeating winds up in the final bake animation.

Any help is appreciated!

**Comment by u3dreal** [comment]
Do you use direct render during baking ?
I can not really relate how that could happen ... i never use direct render ..
