### ISSUE TITLE
Baking has a rare chance of getting permanently stuck

### ISSUE THREAD

**Issue by jericjan** [u3dreal/molecular-plus#25]
I'm not quite sure what happened. I was baking a particle simulation, and I might have pressed spacebar while it still baking. Next thing I know, I couldn't cancel it. I pressed the Cancel button multiple times, but I got nothing. Thankfully, Blender made some backups and everything I needed was recovered. Still, this is a concerning bug. 

Here is a google drive link for the bugged project. Maybe it can help:
https://drive.google.com/file/d/16g0Pl90pqxQaerEGchHE8Fq6HEcUl-Tc/view?usp=share_link

In it, `Sphere.001` has a particle simulation that can't be cancelled. I tried assigning the Free All Bakes button to Quick Favorites but that didn't help.

**Comment by u3dreal** [comment]
that is a param saved with the file ..
goto Properties - Scene - Custom Properties and turn off mol_simrun
Bild
<img width="326" alt="Bildschirmfoto_2023-02-04_um_20 14 37" src="https://user-images.githubusercontent.com/48415446/218139507-2b26a53c-35af-464e-9d4c-fe706b1b0324.png">

**Comment by jericjan** [comment]
That's weird. It currently has zero custom properties so I can't even do that.

**Comment by u3dreal** [comment]
You need to load the scenen first
And then make sure you look in th "SCENE" not the objects.

**Comment by jericjan** [comment]
Sorry, I'm not sure I'm following. My scene is loaded and I am in the Scene tab...

![screenshot](https://img001.prntscr.com/file/img001/rzpjWPcQT-OwZF1tVc5GBA.png)

**Comment by u3dreal** [comment]
Hmm they are just not shown since the sim in not started ..

Try entrering "bpy.context.scene.mol_simrun = False" in the python console ....
<img width="548" alt="Bildschirmfoto 2023-02-11 um 12 01 50" src="https://user-images.githubusercontent.com/48415446/218254562-4456bc8e-2066-4aa7-b8b9-b1a9b10cb702.png">

**Comment by jericjan** [comment]
Alrighty, that did the trick! Thanks so much.
