### ISSUE TITLE
core.py is missing

### ISSUE THREAD

**Issue by tanjary21** [u3dreal/molecular-plus#26]
Hi

Thank you for maintaining and providing such an underrated addon.

I'm trying to install this on Ubuntu but I get the error from line 8 of operators.py saying it cannot import core. I looked into the source code and noticed that there is no core.py file.Think you could pushan update?

**Comment by Lartrax** [comment]
What version of the addon did you download?

**Comment by u3dreal** [comment]
core is not python it is a copiled lib that needs to match your Blenders python version !!!!! 
PLz make sure you get the correct version for your Blender and python version

https://github.com/u3dreal/molecular-plus/releases
