### ISSUE TITLE
is it possible to speed up the process using GPU rather than CPU? 

### ISSUE THREAD

**Issue by Maki9009** [u3dreal/molecular-plus#29]
Would it be possible to run the simulation using GPU hardware rather than CPU? or like an option for people who want to use cpu or gpu? since some might have a faster gpu than their cpu or the otherway around

**Comment by u3dreal** [comment]
Yes if you hire a good GPU developer everything is possible ..
Looks like you have no clue how much work this would be .. sorry but things are not that simple.
