### ISSUE TITLE
Stuck on process

### ISSUE THREAD

**Issue by zegzulka** [u3dreal/molecular-plus#31]
Hi, I ended up being stuck on "processing", the cancel button doesn't work, restarting or removing the add-on also doesn't. 
<img width="239" alt="Screenshot 2023-09-29 at 17 04 30" src="https://github.com/u3dreal/molecular-plus/assets/9516829/e258b865-cb8c-4382-9fbb-39be85619c29">

Any ideas?

**Comment by regiogate** [comment]
exactly the same here...

**Comment by u3dreal** [comment]
You saved during baking ..... set mol_simrun to false in ..

<img width="327" alt="Bildschirmfoto 2023-11-02 um 20 58 48" src="https://github.com/u3dreal/molecular-plus/assets/48415446/69876b25-152d-4043-be6a-0637df472800">

**Comment by u3dreal** [comment]
I will add check on file load to avoid this in future .
