### ISSUE TITLE
Tracepack (most recent call last)

### ISSUE THREAD

**Issue by w1pe0ut** [u3dreal/molecular-plus#32]
I got an Error when I want to activate the plugin :( 
I dont understand anything from this error sooooo yeah haha. 
![Error](https://github.com/u3dreal/molecular-plus/assets/148535011/132aff13-1f7f-455f-ad2b-5785c852e021)

**Comment by u3dreal** [comment]
arm64 achitecture is not supported at the moment Sorry

**Comment by w1pe0ut** [comment]
@u3dreal Ohh okay. Thx for your response 🙏🏼

**Comment by u3dreal** [comment]
OK o double checked ... now it should work
https://github.com/u3dreal/molecular-plus/releases/tag/1.12.1

**Comment by w1pe0ut** [comment]
Sorry for the late response. I cant try everything right now but the error message after installation does not appear anymore. So I think everything is working. When I have some issues when I work with the plug-in I will text you immediately.
Thx for your work! 🙏🏼

**Comment by u3dreal** [comment]
Good to hear thanks for the feedback !
