### ISSUE TITLE
Meshing of particles.

### ISSUE THREAD

**Issue by revehiet** [u3dreal/molecular-plus#33]
Feature request for meshing particle system with geonodes.

1. You click button in menu.
2. It adds a single vertex.
3. It adds "Particle Instance" modifier on it, and assigns the particle system
4. It adds a geonodes setup to convert to volume, then back to mesh.

Example meshing setup:

![meshing](https://github.com/u3dreal/molecular-plus/assets/149735586/6db29a06-8549-4c9b-8d13-5b85c1de8699)

**Comment by u3dreal** [comment]
First step is done .. here .. For now we have a mesh with particle instance modifier that can be used in GeoNodes
https://github.com/u3dreal/molecular-plus/actions/runs/6739448618
more to come

**Comment by u3dreal** [comment]
For now i think this is sufficiant since you can easyly add your own nodegroups now.
You can even use them in assets
