### ISSUE TITLE
Automatically display source object as "Wire".

### ISSUE THREAD

**Issue by revehiet** [u3dreal/molecular-plus#34]
Most of the time you dont want the original mesh, you just want the particles.

What i suggest is adding a checkbox (on by default maybe?) to set the display flag as "Wire".

![wire](https://github.com/u3dreal/molecular-plus/assets/149735586/4797e401-db62-4dc3-ac2a-1a9c72cb2f1b)

**Comment by u3dreal** [comment]
i added wire display to 3D 2D grid and emitter .. now by default .. i like it so no need for optional

Let me know if this works out
https://github.com/u3dreal/molecular-plus/actions/runs/6746037976
