### ISSUE TITLE
Add cache/bake time in panel.

### ISSUE THREAD

**Issue by revehiet** [u3dreal/molecular-plus#35]
Very simple. Just time how long last simulation took onto panel as a statistic. Useful for benchmarking.

**Comment by u3dreal** [comment]
https://github.com/u3dreal/molecular-plus/actions/runs/7153241931

**Comment by u3dreal** [comment]
You mean after the baking ?

**Comment by u3dreal** [comment]
there is alot of benchmark stuff in the console
Also the final time gets reported to INFO window
