### ISSUE TITLE
Update for 4.0

### ISSUE THREAD

**Issue by revehiet** [u3dreal/molecular-plus#40]
Blender update 4.0 introduced addon breaking bugs. Basically not usable with 4.0.

Some of the various errors ive come across:

![4 0_errors](https://github.com/u3dreal/molecular-plus/assets/149735586/ee968c7e-125f-4ef8-9729-a5a1ee0a5bfa)

**Comment by u3dreal** [comment]
nice

**Comment by u3dreal** [comment]
fixed here
https://github.com/u3dreal/molecular-plus/actions/runs/7153241931
