### ISSUE TITLE
Missing core module when enabling addon v1.14.1 on Linux

### ISSUE THREAD

**Issue by peter-vasut** [u3dreal/molecular-plus#46]
Hello, I get following message when trying to enable the add-on:

```
Traceback (most recent call last):
  File "/usr/share/blender/4.0/scripts/modules/addon_utils.py", line 401, in enable
    mod.register()
  File "/home/peter/.config/blender/4.0/scripts/addons/molecularplus/__init__.py", line 39, in register
    from . import properties, ui, operators, creators, addon_prefrences
  File "/home/peter/.config/blender/4.0/scripts/addons/molecularplus/operators.py", line 10, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecularplus' (/home/peter/.config/blender/4.0/scripts/addons/molecularplus/__init__.py)

```

I'm running blender 4.0.2 which includes Python version 3.11.6.

Issue appears to be that the binary core module can't be imported for some reason. I don't know how the linking of compiled code and python works, so this is all the info I could provide.

**Comment by u3dreal** [comment]
Hi you are literally the first one using it on linux for a long time .. so i will have to check on linux .
haven't done that for a while ..

**Comment by u3dreal** [comment]
"I'm running blender 4.0.2 which includes Python version 3.11.6." 
official Blender has 3.10.13 for python.

You will have to compile molecular against python 3.11 yourself.

**Comment by Miner34dev** [comment]
It's back. Addon version 1.15.5 for python 3.11, blender 4.1.1 (from arch repos).
```
Exception in module register(): /home/miner34/.config/blender/4.1/scripts/addons/molecularplus/__init__.py
Traceback (most recent call last):
File "/usr/share/blender/4.1/scripts/modules/addon_utils.py", line 444, in enable
mod.register()
File "/home/miner34/.config/blender/4.1/scripts/addons/molecularplus/__init__.py", line 39, in register
from . import properties, ui, operators, creators, addon_prefrences
File "/home/miner34/.config/blender/4.1/scripts/addons/molecularplus/operators.py", line 9, in <module>
from . import simulate, core
ImportError: cannot import name 'core' from 'molecularplus' (/home/miner34/.config/blender/4.1/scripts/addons/molecularplus/__init__.py)
```

**Comment by u3dreal** [comment]
Probably a Problem between arch linux and ubuntu ( used to compile Molecular ) 
You might have to compile molecular yourself. check the github action for instruction.
Works as expected on ubuntu.

**Comment by Miner34dev** [comment]
I can't compile! I think this might be helpful:
![Screenshot_20240717_201555](https://github.com/user-attachments/assets/f01acb2e-c58c-4aef-bd18-d428cc1ab0d1)
You see, the Python version is 3.12.4! Apparently, the arch package is modified to use the system version of Python.

**Comment by u3dreal** [comment]
Seems your Blender has been compiled with python 3.12.4 .. so just use Blender from original site blender.org
