### ISSUE TITLE
error when clicking on start simulation

### ISSUE THREAD

**Issue by luckychris** [u3dreal/molecular-plus#57]
i got this error, if i click on "start simulation":

<img width="665" alt="image" src="https://github.com/u3dreal/molecular-plus/assets/232549/a59fdf9d-b737-4bcd-a83f-b48b9fd17081">

is there a fix or workaround for this? or did i install a wrong version?

I am working on a Macbook:

<img width="239" alt="image" src="https://github.com/u3dreal/molecular-plus/assets/232549/2d1013fb-7790-4997-912c-ac2dcd51a389">

with Blender 4.2

I would appreciate any help.

**Comment by u3dreal** [comment]
Blender 4.2 is not supported for now . Have to look into it
