### ISSUE TITLE
Tried everything but can't seem to remove the molecular plus from the blender splash screen

### ISSUE THREAD

**Issue by lucianopetrigh** [u3dreal/molecular-plus#59]
Hi,

I removed the molecular plus addon because i don't need it for my work. but since blender 3.0 (now using 4.1.1), the molecular plus stays in the blender splash screen. I removed it from blender addons section (preferences). If someone can help me remove it from the splash screen. thank you im running linux popos 22.04 and i download the blender software as a zip file from the official website.

**Comment by u3dreal** [comment]
No idea Sorry.. what do you mean with stays on the splash screen ? Shouldn't be there at all ...

**Comment by lucianopetrigh** [comment]
![Screenshot from 2024-07-13 11-50-19](https://github.com/user-attachments/assets/11eecdaf-a2bf-4e2e-95d7-06b4478b5454)
how do i remove molecular nodes from the blender splash screen?

**Comment by lucianopetrigh** [comment]
sorry i thought molecular plus is the same as molecular nodes.. i thought it was the same addon

**Comment by u3dreal** [comment]
OK solved
