### ISSUE TITLE
unable to install the latest version on blender 4.2, please help

### ISSUE THREAD

**Issue by astro1df** [u3dreal/molecular-plus#63]
![image](https://github.com/user-attachments/assets/b958d398-557e-4180-997d-38094c0320a5)

**Comment by JamesMallion** [comment]
Any solutions to this? I have the same issue.

**Comment by ramshashaikh** [comment]
Having the same issue

**Comment by JamesMallion** [comment]
I Installed version 1.15.5 https://github.com/u3dreal/molecular-plus/releases/tag/1.15.5 

That works for me

**Comment by hoodFX** [comment]
Facing same issues. By installing 1.15.5 i can install successful, but only emitter option enable. So useless to use it.
I used blender 4.2 and 4.2.1 lts.

**Comment by u3dreal** [comment]
I can not reproduce the problem ... for a workaround install latest and then replace the core.cp311 ... with the one from 1.15.5
Unless someone can really take a look that has the problem there is nothing i can do
For me it work withou problem on 6 different windows sytem .. so i have no clue .
