### ISSUE TITLE
What heppen if par.alive_state == "DYING"?

### ISSUE THREAD

**Issue by yusukeyasui** [u3dreal/molecular-plus#7]
Thank you for your great work! 
While looking at the code, I am seeing one thing I want to make sure.  

In the following loop in simulate.py (https://github.com/u3dreal/molecular-plus/blob/a8c146a212367998e74cd68b99e7578464acd2ea/simulate.py#L46), 

par_alive = []
for par in psys.particles:
    parnum += 1
    if par.alive_state == "UNBORN":
        par_alive.append(2)
    if par.alive_state == "ALIVE":
        par_alive.append(0)
    if par.alive_state == "DEAD":
        par_alive.append(3)

For some particle, if par.alive_state == "DYING", the number of elements in par_alive will be less than parnum. I am wondering if it can cause problem in core.pyx because there seems to be an assumption that the number of elements in par_alive is always equal to parnum?  

If par.alive_state is never set to "DYING", it should be fine.

**Comment by u3dreal** [comment]
Hello yusukeyasui,

it seems to be a mystery if particles ever get to "DYING" state ... i have not found an answer to this yet.
So far there does not seem to be a problem .....

If you feel like having a look at it ... you are more than welcome ... so far it's a bit lonely as a dev here .. :)
Head over to the discord ...

**Comment by yusukeyasui** [comment]
OK, I will let you know if I encounter a problem.
Thanks!
