### ISSUE TITLE
Strange Particle Size Behaviour

### ISSUE THREAD

**Issue by FarbigeWelt** [u3dreal/molecular-plus#70]
latest molecular-plus_1.17.21_311_win.zip
Blender 4.2.3 LTS
Windows 11 32H2
AMD Ryzen 5950X
128 GB RAM
8 GB on each, NVIDIA RTX 2080S, AMD RX 5700 XT

I am pretty sure molecular script was able to deal with particles size and self collision properly.
Again, it has beeen a while since I rendered a beer called "Hinech" with foam using moleculr script and luxcorerender.
The bubbles for the foam have been placed correectly with molecular script.
But with the current version called molecular plus I cannot simulate foam. Maybe its because I'm using linking now. However there is soemthing worng in my opinion with linking distance. It has an effect but it's rather odd. Particles link to each other with a large gap or they overlap. 

The example shows the first case. Enlarge the particles' size in the example and simulate again to get the second case.
[Molecular Plus_Particle Size.zip](https://github.com/user-attachments/files/17926803/Molecular.Plus_Particle.Size.zip)

**Comment by FarbigeWelt** [comment]
Indeed, with the current version particles overlap each other at the bottom of a cylinder. 
Start simulation in the example attached.
[Molecular Plus_Particle Size_only self collision.zip](https://github.com/user-attachments/files/17926907/Molecular.Plus_Particle.Size_only.self.collision.zip)

**Comment by FarbigeWelt** [comment]
.. and strange enough, even a version for Blender 3.3.21 LTS ovelaps particles at the bottom of a cylinder .. I wonder how I managed the simulation with the bubbles abotu 4 years ago ..

**Comment by u3dreal** [comment]
there are two sizes .. the actual size for collison and the size of the halo or object shown..
that actually changed from 3.x to 4.x -- before it was radius on the first and diameter on the last --
since 4.0 that should both be radius .. so they should be the same value !
If they overlap the display size is too big or the other way round ...

**Comment by FarbigeWelt** [comment]
Hi u3dreal

Thank you for your answer. If you use Render As Halo you are right.

If you use Render As Object things are more complicated. There are three different sizes: Particle Scale (a factor) and Object Scale and Object Size, the latter two count if Object Scale is checked. However, to make things easier uncheck Object Scale.

Next, consider there are instanced object's shape (cube, sphere, ico sphere, ..) and Molecule+ substeps, the higher the latter vaule the slower the simulation but the preciser the collisions. 

The distances between or overlapping the particles depend (substeps=4) strongly on the shape of the instanced object: cubes overlap up to 20%, spheres  up to ~10%-15%, ico spheres (subdivision 1) gap about 10% equally.

A shape I found fitting nicely is geodesic: Icosahedron shaped hex and round.

Increasing substeps to 16 improves collision for spheres and icosahedron but neither for cubes nor for ico spheres.

There is another setting for scale: Scale Randomness. The particles get different sizes and what is astonishing Molecule+ can handle this very well for good working shapes.

<img width="856" alt="Bildschirmfoto 2024-11-27 um 14 07 14" src="https://github.com/user-attachments/assets/a23ae6ea-88d0-4d9a-812a-fcca4ab7f4c7">
<img width="636" alt="Bildschirmfoto 2024-11-27 um 16 01 04" src="https://github.com/user-attachments/assets/027960cd-be18-44d7-8d39-cac4e39b2c85">
<img width="284" alt="Bildschirmfoto 2024-11-27 um 16 01 49" src="https://github.com/user-attachments/assets/2c4a8007-c0d2-451c-8474-a90f03a92420">
<img width="290" alt="Bildschirmfoto 2024-11-27 um 16 02 25" src="https://github.com/user-attachments/assets/02c8cfc4-4c40-404a-a6d3-86f30f086833">

Thank you a lot u3dreal supporting this Add-on. It looks great with the N-Menu and other cleaned up menus.

Cheers,
FarbigeWelt
