### ISSUE TITLE
molecular-plus_1.17.21_311_macos_arm64 throws an error when trying to enable add-on

### ISSUE THREAD

**Issue by FarbigeWelt** [u3dreal/molecular-plus#71]
MacBook Air
Apple M1
16 GB
macOS Sonoma V. 14.6.1

Blender 4.3.0, Apple Chip
molecular-plus_1.17.21_311

<img width="935" alt="Bildschirmfoto 2024-12-05 um 10 06 54" src="https://github.com/user-attachments/assets/55b139fa-9dba-4914-bec3-4a06915cd2b8">
<img width="854" alt="Bildschirmfoto 2024-12-05 um 10 08 30" src="https://github.com/user-attachments/assets/c1e135d9-a633-493d-9754-6c85a041fa33">

**Comment by u3dreal** [comment]
Can you try this ?
[https://github.com/u3dreal/molecular-plus/actions/runs/12049053732](url)

I updated macos runner and XCode .. that should fix the bind code problem

**Comment by FarbigeWelt** [comment]
I'd like to try but the link shows this
<img width="1274" alt="Bildschirmfoto 2024-12-05 um 14 14 03" src="https://github.com/user-attachments/assets/dbf78d1e-ce9d-40b3-a9d2-b425dc35fa0e">

**Comment by u3dreal** [comment]
[molecular-plus_1.17.21_311_macos_arm64.zip](https://github.com/user-attachments/files/18023774/molecular-plus_1.17.21_311_macos_arm64.zip)

**Comment by FarbigeWelt** [comment]
Great! I've tested it with a simple particle simulation with self collision and linking at birth. Works all well! THX for fixing!

**Comment by FarbigeWelt** [comment]
Great Support!
