### ISSUE TITLE
Blender 2.93 unable to install

### ISSUE THREAD

**Issue by levybergman** [u3dreal/molecular-plus#9]
unable to install latest version (1.1.4_39_macos and 1.1.4_37m_macos) to Blender 2.93 on Mac OSX
see attached the error message
![Screen Shot 2021-06-02 at 9 34 26 PM](https://user-images.githubusercontent.com/85265718/120572730-76eded80-c3ea-11eb-8771-51f6291c5866.png)

**Comment by u3dreal** [comment]
Hi levy looks like you are missing libgomp. 
A fast fix would be to install brew and then do

brew install gcc

I have to think of a way to distribute the lib along with the addon.
looks like you are the first one using the addon on osx.

**Comment by u3dreal** [comment]
OK i fixed it gomp in now linked statically. Can you try this version ??
[https://github.com/u3dreal/molecular-plus/actions/runs/902463606](url)

**Comment by u3dreal** [comment]
It was time for a release anyway 

https://github.com/u3dreal/molecular-plus/releases/tag/1.1.5

**Comment by levybergman** [comment]
Thanks a lot for your quick reply and fix!! I was able to install on both version (2.92 & 2.93).
I put it on test quickly with the Emitter and 3D Grid as well. I experienced this jiggle in the animation as you can see in the attached screen recording.
Maybe I missed some settings, but still would like to ask if you have any idea how to fix it?
Thanks again, Levy


https://user-images.githubusercontent.com/85265718/120659998-e4366880-c454-11eb-935f-091d3512c339.mp4

**Comment by u3dreal** [comment]
head over to the discord and share the file if possible. That would make things alot easier.

https://discord.com/invite/tAwvNEAfA3

**Comment by levybergman** [comment]
I do.
Thanks
